/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Jugador;
import civitas.JugadorEspeculador;
import civitas.TituloPropiedad;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author albertorobles
 */
public class JugadorVista extends javax.swing.JPanel {
    private Jugador jug;
    /**
     * Creates new form JugadorVista
     */
    public JugadorVista() {
        initComponents();
         
    }

    void setJugador(Jugador j){
        jug_nombre.setText(j.getNombre());
        jug_saldo.setText(""+j.getSaldo());
       
        Color color_actual;
        if(!j.enBancarrota()){
            color_actual = Color.blue;
            this.setBackground(color_actual);
        }
        else{
            color_actual = Color.red;
            this.setBackground(color_actual);
            
        }
            
        if(j.isEncarcelado()){
            jug_encarcelado.setText("SI");
        }
        else{
            jug_encarcelado.setText("NO");
        }
        
        if(j.isEspeculador()){
            jug_especulador.setText("SI");
        }
        else{
            jug_especulador.setText("NO");
        }
        propiedades.setBackground(color_actual);
        
        rellenaPropiedades(j.getPropiedades());
        
        repaint();
        revalidate();
    }
    
    private void rellenaPropiedades (ArrayList<TituloPropiedad> lista) {
// Se elimina la información antigua
        propiedades.removeAll();
   // Se recorre la lista de propiedades para ir creando sus vistas individuales y
    //añadirlas al panel
        if(lista.size()>0)
             propiedades.setBackground(Color.green);
        for (int i=0; i<lista.size(); i++) {
           
            PropiedadVisual vistaPropiedad = new PropiedadVisual();
            vistaPropiedad.setPropiedad(lista.get(i));
            propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
// Se fuerza la actualización visual del panel propiedades y del panel del jugador
        repaint();
        revalidate();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_nom = new javax.swing.JLabel();
        jug_nombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jug_saldo = new javax.swing.JLabel();
        jug_encarcelado = new javax.swing.JLabel();
        jug_especulador = new javax.swing.JLabel();
        propiedades = new javax.swing.JPanel();

        titulo_nom.setText("JUGADOR:");
        titulo_nom.setToolTipText("");
        titulo_nom.setEnabled(false);

        jug_nombre.setForeground(new java.awt.Color(110, 110, 110));
        jug_nombre.setText("jLabel2");

        jLabel1.setText("SALDO:");
        jLabel1.setToolTipText("");
        jLabel1.setEnabled(false);

        jLabel2.setText("ENCARCELADO:");
        jLabel2.setToolTipText("");
        jLabel2.setEnabled(false);

        jLabel3.setText("ESPECULADOR:");
        jLabel3.setEnabled(false);

        jug_saldo.setForeground(new java.awt.Color(110, 110, 110));
        jug_saldo.setText("jLabel4");

        jug_encarcelado.setForeground(new java.awt.Color(110, 110, 110));
        jug_encarcelado.setText("jLabel5");

        jug_especulador.setForeground(new java.awt.Color(110, 110, 110));
        jug_especulador.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titulo_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jug_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jug_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jug_encarcelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jug_especulador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 403, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_nom)
                    .addComponent(jug_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jug_saldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jug_encarcelado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jug_especulador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jug_encarcelado;
    private javax.swing.JLabel jug_especulador;
    private javax.swing.JLabel jug_nombre;
    private javax.swing.JLabel jug_saldo;
    private javax.swing.JPanel propiedades;
    private javax.swing.JLabel titulo_nom;
    // End of variables declaration//GEN-END:variables
}
